<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;
use Illuminate\Support\Facades\Hash;

class StudentSeeder extends Seeder
{
    public function run()
    {
        $students = [
            [
                'first_name' => 'Marko',
                'last_name' => 'Janković',
                'email' => 'marko.jankovic@example.com',
                'phone' => '065123456',
                'date_of_birth' => '2002-03-15',
                'gender' => 'male',
                'student_index' => 'EE-01/2021',
                'year_of_study' => 3,
                'department' => 'Elektrotehnika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Jovana',
                'last_name' => 'Petrović',
                'email' => 'jovana.petrovic@example.com',
                'phone' => '066789123',
                'date_of_birth' => '2003-06-21',
                'gender' => 'female',
                'student_index' => 'RI-02/2022',
                'year_of_study' => 2,
                'department' => 'Računarstvo i informatika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Nikola',
                'last_name' => 'Savić',
                'email' => 'nikola.savic@example.com',
                'phone' => '065987654',
                'date_of_birth' => '2001-11-10',
                'gender' => 'male',
                'student_index' => 'EE-03/2020',
                'year_of_study' => 4,
                'department' => 'Elektrotehnika',
                'status' => 'graduated',
                'password' => 'password',
            ],
            [
                'first_name' => 'Aleksandra',
                'last_name' => 'Kovačević',
                'email' => 'aleksandra.kovacevic@example.com',
                'phone' => '060112233',
                'date_of_birth' => '2002-12-02',
                'gender' => 'female',
                'student_index' => 'RI-04/2021',
                'year_of_study' => 3,
                'department' => 'Računarstvo i informatika',
                'status' => 'active',
                'password' => 'password',
            ],

            [
                'first_name' => 'Vladimir',
                'last_name' => 'Dimitrić',
                'email' => 'vladimir.dimitric@example.com',
                'phone' => '065551122',
                'date_of_birth' => '2003-09-19',
                'gender' => 'male',
                'student_index' => 'EE-05/2022',
                'year_of_study' => 2,
                'department' => 'Elektrotehnika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Sara',
                'last_name' => 'Radić',
                'email' => 'sara.radic@example.com',
                'phone' => '066334455',
                'date_of_birth' => '2004-01-29',
                'gender' => 'female',
                'student_index' => 'RI-03/2023',
                'year_of_study' => 1,
                'department' => 'Računarstvo i informatika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Uroš',
                'last_name' => 'Babić',
                'email' => 'uros.babic@example.com',
                'phone' => '065992211',
                'date_of_birth' => '2001-05-04',
                'gender' => 'male',
                'student_index' => 'EE-06/2020',
                'year_of_study' => 4,
                'department' => 'Elektrotehnika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Milica',
                'last_name' => 'Blagojević',
                'email' => 'milica.blagojevic@example.com',
                'phone' => '060221133',
                'date_of_birth' => '2002-08-12',
                'gender' => 'female',
                'student_index' => 'RI-07/2021',
                'year_of_study' => 3,
                'department' => 'Računarstvo i informatika',
                'status' => 'active',
                'password' => 'password',
            ],

            [
                'first_name' => 'Dušan',
                'last_name' => 'Marić',
                'email' => 'dusan.maric@example.com',
                'phone' => '065880012',
                'date_of_birth' => '2001-07-17',
                'gender' => 'male',
                'student_index' => 'EE-10/2020',
                'year_of_study' => 4,
                'department' => 'Elektrotehnika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Isidora',
                'last_name' => 'Tošić',
                'email' => 'isidora.tosic@example.com',
                'phone' => '066881122',
                'date_of_birth' => '2004-03-03',
                'gender' => 'female',
                'student_index' => 'RI-12/2023',
                'year_of_study' => 1,
                'department' => 'Računarstvo i informatika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Stefan',
                'last_name' => 'Tomić',
                'email' => 'stefan.tomic@example.com',
                'phone' => '065441122',
                'date_of_birth' => '2002-10-26',
                'gender' => 'male',
                'student_index' => 'EE-09/2021',
                'year_of_study' => 3,
                'department' => 'Elektrotehnika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Tamara',
                'last_name' => 'Lukić',
                'email' => 'tamara.lukic@example.com',
                'phone' => '061552233',
                'date_of_birth' => '2001-01-12',
                'gender' => 'female',
                'student_index' => 'RI-08/2020',
                'year_of_study' => 4,
                'department' => 'Računarstvo i informatika',
                'status' => 'graduated',
                'password' => 'password',
            ],

            // 8 more to reach 20:
            [
                'first_name' => 'Petar',
                'last_name' => 'Obradović',
                'email' => 'petar.obradovic@example.com',
                'phone' => '065112233',
                'date_of_birth' => '2003-04-14',
                'gender' => 'male',
                'student_index' => 'EE-14/2022',
                'year_of_study' => 2,
                'department' => 'Elektrotehnika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Ivana',
                'last_name' => 'Kisić',
                'email' => 'ivana.kisic@example.com',
                'phone' => '066991100',
                'date_of_birth' => '2004-02-11',
                'gender' => 'female',
                'student_index' => 'RI-15/2023',
                'year_of_study' => 1,
                'department' => 'Računarstvo i informatika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Danilo',
                'last_name' => 'Šain',
                'email' => 'danilo.sain@example.com',
                'phone' => '065776655',
                'date_of_birth' => '2002-05-20',
                'gender' => 'male',
                'student_index' => 'EE-18/2021',
                'year_of_study' => 3,
                'department' => 'Elektrotehnika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Teodora',
                'last_name' => 'Kosorić',
                'email' => 'teodora.kosoric@example.com',
                'phone' => '061881144',
                'date_of_birth' => '2003-12-30',
                'gender' => 'female',
                'student_index' => 'RI-20/2022',
                'year_of_study' => 2,
                'department' => 'Računarstvo i informatika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Luka',
                'last_name' => 'Davidović',
                'email' => 'luka.davidovic@example.com',
                'phone' => '065554433',
                'date_of_birth' => '2002-06-16',
                'gender' => 'male',
                'student_index' => 'EE-22/2021',
                'year_of_study' => 3,
                'department' => 'Elektrotehnika',
                'status' => 'active',
                'password' => 'password',
            ],
            [
                'first_name' => 'Marija',
                'last_name' => 'Vuković',
                'email' => 'marija.vukovic@example.com',
                'phone' => '066773355',
                'date_of_birth' => '2001-09-07',
                'gender' => 'female',
                'student_index' => 'RI-23/2020',
                'year_of_study' => 4,
                'department' => 'Računarstvo i informatika',
                'status' => 'active',
                'password' => 'password',
            ],
        ];

        foreach ($students as $data) {
            Student::create($data);
        }
    }
}
